config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :posts
  resources :home, only: [:index]
  resources :about_team, only: [:index]
  root "home#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	validates :title, presence: true
	validates :body, presence: true

	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/about_team_controller.rb
class AboutTeamController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@posts = Post.all 
	 end


	private
		def post_params
			params.require(:post).permit(:title, :body)
		end
		
end

app/helpers/about_team_helper.rb
module AboutTeamHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/about_team/index.html.erb
<body>
<main role="main">
	<div class="container">

		<h1 class="color-white"> The Team Of Fatal Void</h1>

		<hr class="featurette-divider">
	
		<div class="top-row">
			<div class="col-md-1"></div>
			<div class="col-md-2"><p class="color-white">CIARAN BRYDEN</p></div> 
			<div class="col-md-2"><p class="color-white">JASPER CHRISTIAN</p></div>
			<div class="col-md-2"><p class="color-white">HASEEB HUSSAIN</p></div>
			<div class="col-md-2"><p class="color-white">ESSA KHAN</p></div>
			<div class="col-md-2"><p class="color-white">MOHAMMED MAHMOOD</p></div>
			<div class="col-md-1"></div>
		</div>

		<div class="seperator">
				<hr class="featurette-divider">
		</div>

		<div class="bot-row">
			<div class="col-md-1"></div>
			<div class="col-md-2"><p class="color-white">ALEXANDER MATTHEWS</p></div>
			<div class="col-md-2"><p class="color-white">MUHAMMED MIAH</p></div>
			<div class="col-md-2"><p class="color-white">LOUIS PAYNE</p></div>
			<div class="col-md-2"><p class="color-white">BARTLOMIEJ ROGALSKI</p></div>
			<div class="col-md-2"><p class="color-white">USAMA SHAZLEE</p></div>
			<div class="col-md-1"></div>
		</div>

	</div>
</main>
</body>

app/views/home/index.html.erb
<!doctype html>
<html lang="en">
  
  <body>

    
    <main role="main">

      <div class="container summary">
        <div class="col-md-12">

          <div class="d-flex justify-content-center">
          <h1 class="display-2 color-white">Play Now For Free!</h1>
          </div>

          <div class="p-5"></div>
          <%= button_to "Install Fatal Void", "/FatalVoidExport.zip", :class => "btn btn-secondary btn-lg btn-block", :method => :get %>

          <div class="p-5"></div>
          <div class="p-5"></div>
        </div>

        <div class="col-md-12">
          <p class="lead color-white">Fatal Void is set 15 years after a devasting war in which a expansionist empire takes over the galaxy. In search of a weapons to keep your small home planet safe from raids, you end up caught in a universe of schemers and men who care only for self gain. </p>
        </div>


      </div>

      
      <!-- Marketing messaging and featurettes
      ================================================== -->
      <!-- Wrap the rest of the page in another container to center all the content. -->

    <hr class="featurette-divider">

    <section id="projects">
    <div class="container">

      <!-- Project One Row -->
      <div class="row justify-content-center no-gutters mb-5 mb-lg-0">
        <div class="col-lg-6">
          <img class="featurette-image img-fluid mx-auto" > <%= image_tag("Snow.png", :class => "img-fluid", :alt => "Town_picture")  %>
        </div>
        <div class="col-lg-6">
          <div class="bg-black text-center h-100 project">
            <div class="ml-4">
              <div class="d-flex h-100">
                <div class="project-text w-100 my-auto text-center text-lg-left">
                  <h4 class="text-white">Intricate Map Design</h4>
                  <p class="mb-0 text-white-50">Maps created by the Fatal Void team are based on real life areas in our universe, this adds a layer of reality to our game instead and allows indepth map design</p>
                  <hr class="d-none d-lg-block mb-0 ml-0">
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Project Two Row -->
      <div class="row justify-content-center no-gutters">
        <div class="col-lg-6">
          <img class="featurette-image img-fluid mx-auto" > <%= image_tag("Modeling_picture.png", :class => "img-fluid", :alt => "Modeling_picture")  %>
        </div>
        <div class="col-lg-6 order-lg-first">
          <div class="bg-black text-center h-100 project">
            <div class="mr-4 p-3">           
              <div class="d-flex h-100">
                <div class="project-text w-100 my-auto text-center text-lg-right">
                  <h4 class="text-white">Detailed Modeling</h4>
                  <p class="mb-0 text-white-50">Like the Maps, the Models are also created by the Fatal Void team to enhance the user experience and to guide them through the mysterious story</p>
                  <hr class="d-none d-lg-block mb-0 ml-0">
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Project Three Row -->
      <div class="row justify-content-center no-gutters mb-5 mb-lg-0">
        <div class="col-lg-6">
          <img class="featurette-image img-fluid mx-auto" > <%= image_tag("Forest.png", :class => "img-fluid", :alt => "Forest_picture")  %>
        </div>
        <div class="col-lg-6">
          <div class="bg-black text-center h-100 project">
            <div class="ml-4 p-3">
              <div class="d-flex h-100">
                <div class="project-text w-100 my-auto text-center text-lg-left">
                  <h4 class="text-white">Inventive Game Mechanics</h4>
                  <p class="mb-0 text-white-50">In the Fatal Void universe, enemies are not your only problem. Nature itself has been plagued and you require hydrogen sulfide to stay alive else die to the elements, adding a layer of time management to the game.</p>
                  <hr class="d-none d-lg-block mb-0 ml-0">
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>


    </div>
  </section>

  <hr class="featurette-divider">

  <div class="container summary">
    <div class="col-lg-6">
        <img class="featurette-image img-fluid mx-auto" > <%= image_tag("Volcano.png", :class => "img-fluid", :alt => "Volcano_picture")  %>
    </div>
    <div class="col-lg-6">
        <img class="featurette-image img-fluid mx-auto" > <%= image_tag("Sand.png", :class => "img-fluid", :alt => "Sand_picture")  %>
    </div>
  </div>

  </main>
  

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
  
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fatal Void</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Bootstrap ref-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>

  <body>
    <%= render 'shared/header'%>
    <%= render 'shared/alerts'%>
    <%= yield %>
    <%= render 'shared/footer'%>
  </body>
</html>

app/views/posts/index.html.erb
<body>
<% @posts.each do |post| %>
 <div class="row">
  <div class="col-xs-8 col-xs-offset-2">
   <div class="well well-lg">
    <div class="post-title">
    	<td><%= post.title%> </td>
    </div>
    <div class="created-at">
      <td style="align-content: right"><%= post.created_at %></td>
    </div>
    
    <div class="post-body">
    	<span><td><%= simple_format post.body%></td></span>
    </div>
   </div>
  </div>
 </div>
<% end %>
</body>

app/views/posts/show.html.erb
<div class = "container post-container">
	
	<div class="row">

		<div class="col-lg-12">
			<h class="page-header"><%= @post.title %>
				<small>Item Subheading</small>
			</h>
		</div>
	</div>


	<div class="row">

		<div class="col-lg-8">
			<%#= image_tag @post.image, class: 'img-responsive' %>
		</div>

		<div class="col-lg-4">
			<h3>blog description</h3>
			<%= @post.body %>
		</div>
	</div>

	<div class="row">
		<div class="col-lg-12">
			<h3 class="page-header">related blogs</h3>
		</div>

		<% @post.each do |post| %>
			<div class = "col-sn-3 col-xs-6">
				<%= link_to post_path {post} do %>
					<%= image_tag post.image, class: 'img-responsive portfolio-item'%>
				<% end %>
			</div>
		<% end %>
	</div>

</div>

app/views/shared/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/shared/_footer.html.erb
<hr class="featurette-divider">
<footer class="container">
	
	
		<p style="text-align: center; color: white;">&copy; 2017-2018 Fatal Void, Inc. <!-- <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p> -->
</footer>

app/views/shared/_header.html.erb
<header class="fixed-top ">
 <nav class="navbar navbar-expand-md bg-dark navbar-dark">
  <!-- Brand -->
  <a class="navbar-brand nav-link" href="#"><%= image_tag("FVlogo.png", :size => "50x30", :alt => "logo header")  %></a>

  <!-- Toggler/collapsibe Button -->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>

  <!-- Navbar links -->
  <div class="collapse navbar-collapse" id="collapsibleNavbar">
    <ul class="navbar-nav" style="float:right">
      <li class="nav-item">
        <a class="nav-link" href="/">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/posts">Blog</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/about_team">About the team</a>
      li>
    </ul>
  </div>
</nav> 

</header> 